---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

deploy:
  provider: npm
  email: tobias.bieniek@gmx.de
  api_key:
    secure: V/2EC1mCfWuYui+MyzrOnZqCWhwJDTEyhsrxlAPIN0T/BbHQdFgYlu+V4Pi03D/Mn0/0x50pcRmvA9A2SfylollRRTZNlnsHvc9QVT+SAp5ww49umhbOLUlEa9+HvufT1U8+t5kUYzBJ8EJJb0fXpqtpvgdf6Q5ZFeOiQ783lYg=
  on:
    tags: true
    repo: ember-cli/ember-cli-mocha
